server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/Maria0696/microservicios
          search-paths: config-data
  application:
    name: config-service